# Predict without pipeline 

In [82]:
import pickle 
import numpy as np 

In [84]:
from sklearn.preprocessing import OneHotEncoder

In [86]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [88]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7) 

In [90]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [112]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\Subham\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [114]:
test_input_sex

array([[0., 1.]])

In [116]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [118]:
test_input_embarked

array([[0., 0., 1.]])

In [120]:
test_input_age = test_input[:,2].reshape(1,1)


In [122]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)


In [124]:
test_input_transformed.shape

(1, 10)

In [126]:
clf.predict(test_input_transformed)

array([1], dtype=int64)

In [128]:
# Here we can observe that we need to do all the transformations again in model testing that we did during model training 